### ISSUE TITLE
opencv build error by dockfile.

### ISSUE THREAD

**Issue by chenin-wang** [NVlabs/BundleSDF#89]
a lot error appeare when build  opencv using the docker by dockfile.

nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).

/opencv/modules/cudastereo/src/cuda/stereobm.cu(458): warning: function "tex2D(texture<T, 2, cudaReadModeNormalizedFloat>, float, float) [with T=unsigned char]"
/usr/local/cuda/include/texture_fetch_functions.h(209): here was declared deprecated

![image](https://github.com/NVlabs/BundleSDF/assets/88609203/1c8e1404-6541-4c94-9efc-043a85e22ae0)

/usr/local/cuda/include/cuda_runtime_api.h:8717:46: note: declared here
 8717 | extern __CUDA_DEPRECATED __host__ cudaError_t CUDARTAPI cudaUnbindTexture(const struct textureReference *texref);
![image](https://github.com/NVlabs/BundleSDF/assets/88609203/e6880749-0c4a-4ab8-8171-148840449ab6)

**Comment by chenin-wang** [comment]
FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04 in dockerfile

**Comment by chenin-wang** [comment]
thanks for your reply. There is just a little concern about whether these deprecated code will affect the operation of OpenCV CUDA

**Comment by chenin-wang** [comment]
https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/docker/dockerfile#L31C13-L31C14

I make a little modification for 3090.
 -DCUDA_ARCH_BIN=8.6
 -DCMAKE_CXX_FLAGS=-std=c++14

`cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA_STUBS=OFF -DBUILD_DOCS=OFF -DWITH_MATLAB=OFF -Dopencv_dnn_BUILD_TORCH_IMPORTE=OFF -DCUDA_FAST_MATH=ON  -DMKL_WITH_OPENMP=ON -DOPENCV_ENABLE_NONFREE=ON -DWITH_OPENMP=ON -DWITH_QT=ON -WITH_OPENEXR=ON -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_cudacodec=OFF -DINSTALL_PYTHON_EXAMPLES=OFF  -DWITH_TIFF=OFF -DWITH_WEBP=OFF -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -DCMAKE_CXX_FLAGS=-std=c++14 -DENABLE_CXX11=OFF  -DBUILD_opencv_xfeatures2d=ON -DOPENCV_DNN_OPENCL=OFF -DWITH_CUDA=ON -DCUDA_ARCH_BIN=8.6 -DWITH_OPENCL=OFF &&\`

**Comment by SRDdev** [comment]
> https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/docker/dockerfile#L31C13-L31C14
> 
> I make a little modification for 3090. -DCUDA_ARCH_BIN=8.6 -DCMAKE_CXX_FLAGS=-std=c++14
> 
> `cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA_STUBS=OFF -DBUILD_DOCS=OFF -DWITH_MATLAB=OFF -Dopencv_dnn_BUILD_TORCH_IMPORTE=OFF -DCUDA_FAST_MATH=ON -DMKL_WITH_OPENMP=ON -DOPENCV_ENABLE_NONFREE=ON -DWITH_OPENMP=ON -DWITH_QT=ON -WITH_OPENEXR=ON -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_cudacodec=OFF -DINSTALL_PYTHON_EXAMPLES=OFF -DWITH_TIFF=OFF -DWITH_WEBP=OFF -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -DCMAKE_CXX_FLAGS=-std=c++14 -DENABLE_CXX11=OFF -DBUILD_opencv_xfeatures2d=ON -DOPENCV_DNN_OPENCL=OFF -DWITH_CUDA=ON -DCUDA_ARCH_BIN=8.6 -DWITH_OPENCL=OFF &&\`

@chenin-wang thanks this worked for me !
